# -*- coding: utf-8 -*-
RES = """<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:orientation="vertical"
    android:background="{tb}">
 <LinearLayout
  android:layout_height="wrap_content"
  android:layout_width="match_parent"
  android:layout_weight="1"
  android:gravity="center"
  android:orientation="vertical">
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="L"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="A"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="M"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r1c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="A"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="C"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="Q"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="U"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="A"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="R"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="R"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="D"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="C"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r2c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="W"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="Y"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="F"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="V"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="X"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r3c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="H"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="A"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="L"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="F"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="B"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="F"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r4c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="P"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="A"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="R"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="U"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r5c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="X"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="H"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="R"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r6c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="F"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="U"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="R"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="F"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="V"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="W"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r7c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="I"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="G"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="H"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="L"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="V"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r8c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="V"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="W"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="L"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="V"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r9c11"/>
  </LinearLayout>
  <LinearLayout
   android:layout_height="wrap_content"
   android:layout_width="match_parent"
   android:orientation="horizontal">
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="T"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c1"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c2"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="N"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c3"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="S"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c4"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="E"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c5"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c6"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="C"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c7"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="L"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c8"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="O"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c9"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="C"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c10"/>
   <Button
    android:textSize="{ts}"
    android:clickable="false"
    android:layout_height="match_parent"
    android:text="K"
    android:textStyle="bold"
    android:textColor="{tc}"
    android:layout_weight="1"
    android:background="{tb}"
    android:id="@+id/r10c11"/>
  </LinearLayout>
 </LinearLayout>
</LinearLayout>"""